# Generated by Django 5.2.17 on 2026-09-04 07:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_name', models.CharField(default='calendar', help_text='Lucide icon name (strictly no emoji)', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('pax_capacity', models.PositiveIntegerField(default=100)),
                ('specifications', models.TextField(help_text='Itemized specifications (comma or newline separated)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin / Platform Operator')], default='CUSTOMER', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('event_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('escrow_status', models.CharField(choices=[('PENDING_PAYMENT', 'Menunggu Pembayaran Escrow'), ('HELD', 'Dana Aman Ditahan di Escrow'), ('MILESTONE_1_PAID', 'Termin 1 (DP 30%) Dicairkan'), ('MILESTONE_2_PAID', 'Termin 2 (Pelaksanaan 40%) Dicairkan'), ('COMPLETED', 'Event Sukses & Pelunasan 30% Selesai'), ('FROZEN', 'Escrow Dibekukan (Dispute Aktif)'), ('REFUNDED', 'Dana Dikembalikan ke Customer (Garansi Finansial)')], default='PENDING_PAYMENT', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendorpackage')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('reason', models.TextField(help_text='Rincian keluhan atau kelalaian vendor')),
                ('evidence_text', models.TextField(blank=True, help_text='Link bukti atau rincian saksi/fakta lapangan')),
                ('status', models.CharField(choices=[('OPEN', 'Dispute Diajukan - Escrow Dibekukan'), ('INVESTIGATING', 'Sedang Dimediasi / Investigasi Tim Vendorama'), ('REFUNDED_TO_CUSTOMER', 'Garansi Finansial Disetujui: 100% Refund ke Customer'), ('SETTLED_PARTIAL', 'Penyelesaian Parsial Disepakati'), ('REJECTED', 'Dispute Ditolak - Payout Dilanjutkan')], default='OPEN', max_length=30)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('penalty_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='core.bookingorder')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Ditahan di Escrow'), ('REQUESTED', 'Pencairan Diajukan Vendor'), ('RELEASED', 'Dana Dicairkan ke Vendor'), ('DISPUTED', 'Ditahan karena Sengketa')], default='HELD', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.bookingorder')),
            ],
            options={
                'ordering': ['milestone_index'],
            },
        ),
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('estimated_pax', models.PositiveIntegerField(default=100)),
                ('budget_min', models.DecimalField(decimal_places=0, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=0, max_digits=12)),
                ('selected_services', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_plans', to=settings.AUTH_USER_MODEL)),
                ('event_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventSavingsVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('target_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_vaults', to=settings.AUTH_USER_MODEL)),
                ('event_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_vault', to='core.eventplan')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(default='Virtual Account (Escrow Vault)', max_length=50)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.eventsavingsvault')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('anonymized_code', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(default='Jakarta', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('pic_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_vetted', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Vetted'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended / Penalized')], default='PENDING', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_completed_events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='core.eventcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendorpackage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.vendorprofile'),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendorprofile'),
        ),
        migrations.CreateModel(
            name='PlannerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.DecimalField(decimal_places=0, default=150000, max_digits=10)),
                ('is_unlocked', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_accesses', to=settings.AUTH_USER_MODEL)),
                ('event_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_unlocks', to='core.eventplan')),
            ],
            options={
                'unique_together': {('customer', 'event_plan')},
            },
        ),
    ]
