# Generated by Django 5.2.17 on 2026-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrowmilestone',
            name='order',
        ),
        migrations.RemoveField(
            model_name='bookingorder',
            name='escrow_status',
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Nominal komisi platform', max_digits=12),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Persentase komisi platform yang diambil dari vendor (misal 10.00%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='commission_status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Settlement'), ('PAID', 'Komisi Terbayar')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Konfirmasi Vendor'), ('CONFIRMED', 'Dikonfirmasi Vendor'), ('COMPLETED', 'Event Selesai'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='vendor_net_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pendapatan bersih yang diterima vendor setelah potongan komisi', max_digits=12),
        ),
        migrations.DeleteModel(
            name='DisputeTicket',
        ),
        migrations.DeleteModel(
            name='EscrowMilestone',
        ),
    ]
