# Generated by Django 5.2.17 on 2026-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_escrowmilestone_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTemplateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Aktif = halaman template gratis bisa dibuka & file bisa diunduh. Nonaktif = halaman mengembalikan 404.')),
                ('original_price', models.DecimalField(decimal_places=0, default=15000, help_text='Harga coret yang ditampilkan (misal 15000 = Rp 15.000). Harga bayar selalu Rp 0.', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free template settings',
                'verbose_name_plural': 'Free template settings',
            },
        ),
    ]
