# Generated by Django 5.2.17 on 2026-09-10 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_freetemplatelead'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode persis seperti di Shopee (huruf besar disarankan)', max_length=32, unique=True)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Berapa hari langganan bertambah per redeem')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Berapa kali kode ini bisa dipakai total')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, help_text='Opsional: kode kedaluwarsa tanggal ini', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_until',
            field=models.DateField(blank=True, help_text='Langganan premium aktif sampai tanggal ini', null=True),
        ),
        migrations.AddField(
            model_name='freetemplatelead',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True = e-mail lolos verifikasi OTP'),
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateField(help_text='Langganan aktif sampai tanggal ini')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.voucher')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
