# Generated by Django 5.2.17 on 2026-09-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverification_voucher_customuser_premium_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidTemplateDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
