# Generated by Django 5.2.17 on 2026-09-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_templatedownloadcode_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('OPERATOR', 'Operator / CS Shopee'), ('ADMIN', 'Admin / Platform Operator')], default='CUSTOMER', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='device_type',
            field=models.CharField(blank=True, default='', help_text='Mobile / Desktop / Tablet', max_length=50),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Waktu unduh file', null=True),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='downloaded_category',
            field=models.ForeignKey(blank=True, help_text='Kategori template yang akhirnya diunduh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_codes', to='core.eventcategory'),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='first_visited_at',
            field=models.DateTimeField(blank=True, help_text='Waktu pertama kali pembeli membuka link web', null=True),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Waktu aktivitas terakhir di web', null=True),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='last_page_viewed',
            field=models.CharField(blank=True, default='', help_text='Halaman terakhir yang dilihat', max_length=255),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Durasi berada di web dalam detik'),
        ),
        migrations.AlterField(
            model_name='templatedownloadcode',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Frekuensi pembukaan halaman web'),
        ),
        migrations.CreateModel(
            name='ExcelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul lengkap / headline template', max_length=200)),
                ('slug', models.SlugField(help_text='Slug URL template', unique=True)),
                ('subheadline', models.TextField(blank=True, default='', help_text='Deskripsi singkat / subheadline manfaat')),
                ('target_audience', models.CharField(blank=True, default='', help_text='Target pengguna (misal: Calon Pengantin & WO)', max_length=255)),
                ('estimated_savings', models.CharField(blank=True, default='', help_text='Estimasi penghematan (misal: Hemat s/d Rp 15 - 30 Juta)', max_length=255)),
                ('key_perks', models.JSONField(blank=True, default=list, help_text='Daftar checklist keunggulan (JSON array of strings)')),
                ('file', models.FileField(blank=True, help_text='File master .xlsx kustom (opsional; jika kosong maka otomatis digenerate oleh sistem)', null=True, upload_to='excel_templates/')),
                ('shopee_product_url', models.URLField(blank=True, default='', help_text='Tautan produk di Shopee (opsional)')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif di katalog publik')),
                ('downloads_count', models.PositiveIntegerField(default=0, help_text='Akumulasi total unduhan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='Kategori event yang diasosiasikan dengan template ini', on_delete=django.db.models.deletion.CASCADE, related_name='excel_template', to='core.eventcategory')),
            ],
            options={
                'verbose_name': 'Excel Template',
                'verbose_name_plural': 'Excel Templates',
                'ordering': ['category__name'],
            },
        ),
    ]
