"""
Django settings for vendorama project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Override via DJANGO_SECRET_KEY env var in production.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-hh97f^!)+ux)#=^&wuwyr&9$f$lgto+u717kl#@brey!@g_p&$')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

AUTH_USER_MODEL = 'core.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vendorama.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_config',
            ],
            'builtins': [
                'core.templatetags.currency_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendorama.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Paid Planner fee (single source of truth, overridable via env).
PLANNER_UNLOCK_FEE = int(os.environ.get('PLANNER_UNLOCK_FEE', '150000'))

# Outgoing e-mail (OTP verifikasi + notifikasi). Default: console (cetak ke
# terminal, cocok untuk development). Produksi: set EMAIL_BACKEND ke
# 'django.core.mail.backends.smtp.EmailBackend' + kredensial SMTP di bawah.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Vendoraman <noreply@vendoraman.id>')

# Canonical public URL of the site (no trailing slash). Used for sitemap,
# social preview tags and absolute links. Override in production.
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000').rstrip('/')

# Link toko/voucher Shopee (ganti dengan URL toko Anda).
# Dipakai di halaman template gratis untuk promo langganan.
SHOPEE_VOUCHER_URL = os.environ.get('SHOPEE_VOUCHER_URL', 'https://shopee.co.id/toko-anda').rstrip('/')

# Optional analytics ID (e.g. GA4 "G-XXXXXXX" or Plausible domain).
# Empty = no tracking snippet rendered.
ANALYTICS_ID = os.environ.get('ANALYTICS_ID', '').strip()

# HTTPS + cookie hardening. Enable in production behind TLS by setting
# DJANGO_SECURE_SSL_REDIRECT=True (and DJANGO_SECURE_HSTS_SECONDS, default 1 year).
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000' if SECURE_SSL_REDIRECT else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'https://vendoraman.vitnite.cloud,http://vendoraman.vitnite.cloud,http://127.0.0.1:8020'
    ).split(',') if o.strip()
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Unfold Modern Admin Configuration
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Vendoraman Admin",
    "SITE_HEADER": "Vendoraman",
    "SITE_SUBHEADER": "Pusat Kendali Platform & Data Management",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard & Platform",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Admin Index",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Dashboard Komisi",
                        "icon": "analytics",
                        "link": reverse_lazy("admin_dashboard"),
                    },
                    {
                        "title": "Tracking Kode Shopee",
                        "icon": "confirmation_number",
                        "link": reverse_lazy("admin_download_codes"),
                    },
                    {
                        "title": "Katalog Template Publik",
                        "icon": "public",
                        "link": reverse_lazy("excel_templates_catalog"),
                    },
                ],
            },
            {
                "title": "Transaksi & Keuangan",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Pesanan Booking (Order)",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:core_bookingorder_changelist"),
                    },
                    {
                        "title": "Download Template Berbayar",
                        "icon": "shopping_bag",
                        "link": reverse_lazy("admin:core_paidtemplatedownload_changelist"),
                    },
                    {
                        "title": "Kupon & Voucher Diskon",
                        "icon": "local_offer",
                        "link": reverse_lazy("admin:core_voucher_changelist"),
                    },
                    {
                        "title": "Riwayat Redeem Voucher",
                        "icon": "history",
                        "link": reverse_lazy("admin:core_voucherredemption_changelist"),
                    },
                ],
            },
            {
                "title": "Mitra Vendor & Layanan",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Profil Mitra Vendor",
                        "icon": "storefront",
                        "link": reverse_lazy("admin:core_vendorprofile_changelist"),
                    },
                    {
                        "title": "Paket Layanan Vendor",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:core_vendorpackage_changelist"),
                    },
                    {
                        "title": "Kategori Event",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_eventcategory_changelist"),
                    },
                ],
            },
            {
                "title": "Template Excel & Unduhan",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Katalog Master Template",
                        "icon": "table_chart",
                        "link": reverse_lazy("admin:core_exceltemplate_changelist"),
                    },
                    {
                        "title": "Kode Akses Unduh (Shopee)",
                        "icon": "vpn_key",
                        "link": reverse_lazy("admin:core_templatedownloadcode_changelist"),
                    },
                    {
                        "title": "Log Unduhan & IP Pelanggan",
                        "icon": "file_download",
                        "link": reverse_lazy("admin:core_templatedownloadlog_changelist"),
                    },
                    {
                        "title": "Pengaturan Template Gratis",
                        "icon": "tune",
                        "link": reverse_lazy("admin:core_freetemplatesettings_changelist"),
                    },
                    {
                        "title": "Leads Template Gratis",
                        "icon": "contact_page",
                        "link": reverse_lazy("admin:core_freetemplatelead_changelist"),
                    },
                ],
            },
            {
                "title": "Pengguna & Akun",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Data Pengguna (User)",
                        "icon": "group",
                        "link": reverse_lazy("admin:core_customuser_changelist"),
                    },
                    {
                        "title": "Verifikasi Email OTP",
                        "icon": "mark_email_read",
                        "link": reverse_lazy("admin:core_emailverification_changelist"),
                    },
                    {
                        "title": "Rencana Event (Planner)",
                        "icon": "event_note",
                        "link": reverse_lazy("admin:core_eventplan_changelist"),
                    },
                    {
                        "title": "Akses Berbayar Planner",
                        "icon": "lock_open",
                        "link": reverse_lazy("admin:core_planneraccess_changelist"),
                    },
                    {
                        "title": "Tabungan Event (Vault)",
                        "icon": "savings",
                        "link": reverse_lazy("admin:core_eventsavingsvault_changelist"),
                    },
                    {
                        "title": "Setoran Tabungan",
                        "icon": "payments",
                        "link": reverse_lazy("admin:core_savingsdeposit_changelist"),
                    },
                ],
            },
        ],
    },
}
